add_newline = true

format = """
$directory$git_branch$git_status
$character"""

right_format = "$username[@](white)$hostname $time"

# -----------------
# Left prompt (ALL green)
# -----------------

[directory]
style = "green"
format = "[$path ]($style)"
truncate_to_repo = false
truncation_length = 0

[git_branch]
style = "green"
symbol = ""
format = "[on $branch ]($style)"

[git_status]
style = "green"
format = "[$all_status$ahead_behind]($style)"

# -----------------
# Right prompt (green)
# -----------------

[username]
show_always = true
style_user = "cyan"
style_root = "red bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "cyan"
format = "[$hostname]($style)"

[time]
disabled = false
time_format = "%I:%M:%S %p"
style = "red"
format = "[$time]($style)"

# -----------------
# Prompt char (green)
# -----------------

[character]
success_symbol = "[>](green) "
error_symbol = "[>](red) "
